### ISSUE TITLE
Extension error

### ISSUE THREAD

**Issue by adh47** [staruml/staruml-xmi#12]
After upgrade to version 3 for Mac OS X I found extension error in extension manager.
Removing and re-installing did not fix the problem.
<img width="699" alt="bildschirmfoto 2018-06-01 um 15 08 47" src="https://user-images.githubusercontent.com/39414834/40842302-bb9d39ac-65ad-11e8-90df-98d29a5b2623.png">

Even the menu shows xmi export nothing happens. Also no error message.
<img width="527" alt="bildschirmfoto 2018-06-01 um 15 06 46" src="https://user-images.githubusercontent.com/39414834/40842262-8fea5f9c-65ad-11e8-8a32-e913da9a0741.png">

**Comment by adh47** [comment]
Problem solved:
Missing dependencies.

**Comment by niklauslee** [comment]
Removed `filenamify` module dependencies.
Please remove the extensions and then install again.

**Comment by adh47** [comment]
Hallo,

thanks, for your help and sorry for late replay.

I removed the extension and installed it again.

It is working fine.

Thanks again,

Regards,

Alex

-- 
Alexander Haag
Sent with Airmail

Am 5. Juni 2018 um 09:57:07, Minkyu Lee (notifications@github.com) schrieb:

Removed filenamify module dependencies.
Please remove the extensions and then install again.
